metadatadeploy/objects/Claim__c.object
<CustomObject>
    <label>Claim</label>
    <nameField>
        <label>Claim Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Housing Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Claims</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_of_Incident__c</fullName>
        <label>Incident Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description_of_Incident__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Notification_Date__c</fullName>
        <label>Notification Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Policy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Policy</label>
        <referenceTo>Policy__c</referenceTo>
        <relationshipLabel>Claims</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type_of_Loss__c</fullName>
        <label>Type of Loss</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Break-in</fullName>
                </value>
                <value>
                    <fullName>Fire</fullName>
                </value>
                <value>
                    <fullName>Fire Alarm</fullName>
                </value>
                <value>
                    <fullName>Stock damage</fullName>
                </value>
                <value>
                    <fullName>Water damage</fullName>
                </value>
                <value>
                    <fullName>Vandalism</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

metadatadeploy/objects/Policy__c.object
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Policies</relationshipLabel>
        <relationshipName>Policies</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

metadatadeploy/classes/makeaClaim_controller.cls
public with sharing class  makeaClaim_controller  {
    
     @Auraenabled
    public static List<Account> getHousingcompanyrecords(){
        List<Account> acc = [select Id,Name from Account];
        return acc;
    }
    @Auraenabled
     public static List<Policy__c> getPolicyrecords(String Id){
        List<Policy__c> p = [select Id,Name from Policy__c where Account__c=:Id];
         System.debug('policy='+p);
        return p;
    }

    @AuraEnabled

 public static void saveClaim(String name, Date ndate,Date incident,String description,Id policy,Id householdAccount,String Tol)

    {
      Claim__c cl= new Claim__c();
        cl.Name=name;
        cl.Date_of_Incident__c=incident;
        cl.Description_of_Incident__c=description;
        cl.Policy__c=policy;
        cl.Type_of_Loss__c=Tol;
        cl.Notification_Date__c=ndate;
        cl.Account__c=householdAccount;
        Database.insert(cl,true);
    }
    @AuraEnabled 
   public static ListView getListViews(){
       return [SELECT Id, Name FROM ListView WHERE SobjectType = 'Claim__c' LIMIT 1].get(0);
    }
    
    @AuraEnabled
    public static string getRecordtypename(){
        List<RecordType> rec=[select id,name from RecordType where SobjectType = 'Claim__c' limit 1];
            String name = rec[0].name;
            return name;
    }
}